openapi: 3.0.0
info:
  title: MCP Metrovalencia API
  description: API para consultar horarios y rutas del metro de Valencia.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /arrival:
    get:
      summary: Obtener horarios de llegada para una estaci贸n
      parameters:
        - name: stationId
          in: query
          description: ID de la estaci贸n
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de horarios de llegada
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    linea:
                      type: string
                    destino:
                      type: string
                    minutos:
                      type: string
  /route:
    get:
      summary: Obtener rutas entre dos estaciones
      parameters:
        - name: from
          in: query
          description: ID de la estaci贸n de origen
          required: true
          schema:
            type: integer
        - name: to
          in: query
          description: ID de la estaci贸n de destino
          required: true
          schema:
            type: integer
        - name: date
          in: query
          description: Fecha de la consulta (formato YYYY-MM-DD)
          required: false
          schema:
            type: string
        - name: time
          in: query
          description: Hora de inicio de la consulta (formato HH:MM)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la ruta
          content:
            application/json:
              schema:
                type: object
                properties:
                  origen:
                    type: string
                  destino:
                    type: string
                  total:
                    type: integer
                  combinaciones:
                    type: array
                    items:
                      type: object
                      properties:
                        salida:
                          type: string
                        trayecto:
                          type: array
                          items:
                            type: object
                            properties:
                              hora:
                                type: string
                              tren:
                                type: string
                              linea:
                                type: string
                              destino:
                                type: string
                              desde:
                                type: string
                              hasta:
                                type: string
                              duracion:
                                type: integer
                              llegada:
                                type: string
